env:
  node: true
  commonjs: true
  es6: true
extends:
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  linebreak-style: [0, "error", "windows"],
  max-len: [2, {"code": 190 }]
}
