language: node_js
node_js:
  - '12'
deploy:
  provider: heroku
  app:
    develop: backend-linkedpet_dev
  strategy: git
  api_key:
    secure: YSLelnAPtIBETMaocAL4I0scaoL7pCS8MNaXHUqLw4Tc5p/13kL7iSk1i6/zuS/eXevtzOBWJzqlqdf/6KkRaywB8XGZlh3m4QxqjCFmu5o/pYODr9a/04HsIWY/o/K53OKOrMmSy6AxvZ5D454YDpE4efYGNRDf69hjSWKlC0qlOLe7730mvR7Qy04ejNS8JmRYHXRte5lAuNvPdiJeVqToYlKjaDnHuK1IhlYn77pH+6ShyFK8woYcb5c+TxAYQq5wo5ErCY8syKSB8+lng6d3SyB9kkmUy+dZXkNsOTldsHIbCurAUvVjrN4D2DeLI3F80uYcQ7AhyV3mEJ2xeDcF961ft+vqgotXgHTJsHt32RpuwfUnOkW2NVgvCtL8QxWfvDMTpm1vNIsn7dYqqtsc1A2oW9zrQ0Uk3OedFiyQaMdn1ndIpyviSXE8AGupPjfC6QHkHvyL0/0S4V0CnBhGIPH4ed2bVF/j95bQNIxaJD/cLcr8C4eOTBw8RxU8XfY57H7JbZfZnpvDi7aeRxjRT3pfISW+CNpEqKdg2sbdhgGi83gtH05aspAGavmJe3HHW4cW5824pvb8LMyUgcbxitjft88UHTXcZIc0F2fQlcOuztwS9UBzLaCHGi08AkzEFKrW0DfLXGAyMaGkoSoYMHN5O6yuFoP2lE8M+1Q=
  run:
  - npm install
