/* eslint-disable max-len */
exports.seed = async (knex) => {
  // Deletes ALL existing entries
  await knex.raw(`SET FOREIGN_KEY_CHECKS = 0;`);
  await knex('shelter').del();
  await knex('adoption').del();
  await knex('administrator').del();
  await knex('breeding').del();
  await knex('review').del();
  await knex('request').del();
  await knex('publication').del();
  await knex('particular').del();
  await knex('moderator').del();
  await knex('vet').del();
  await knex('user_account').del();
  await knex.raw(`SET FOREIGN_KEY_CHECKS = 1;`);

  // user_account
  await knex('user_account').insert([
    // shelter
    {
      id: 1,
      user_name: 'elRefugioEscuela',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a', // hola
      role: 'shelter',
      activate: true,
      name: 'Sofia',
      email: 'sofia@elrefugioescuela.com',
      address: 'Calle San Vicente, nº 9. Sevilla.',
      telephone: '687444976',
      optional_photo: null,
    },
    {
      id: 2,
      user_name: 'arcaSevilla',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Arca Sevilla',
      email: 'arcasevilla@gmail.com',
      address: 'Calle Miguel CID, nº 3. Sevilla.',
      telephone: '954478512',
      optional_photo: null,
    },
    {
      id: 3,
      user_name: 'protectoraDoggy',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: false,
      name: 'Protectora Doggy',
      email: 'info@protectoradoggy.org',
      address: 'Calle ejemplo 3',
      telephone: '954896523',
      optional_photo: 'http://www.protectoradoggy.org/',
    },
    // administrator
    {
      id: 4,
      user_name: 'mariaCuevas',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: false,
      name: 'María',
      email: 'mariacuevas@gmail.com',
      address: 'Avenida de la Aviación, nº3. Sevilla.',
      telephone: '688765498',
      optional_photo: null,
    },
    {
      id: 5,
      user_name: 'danielNegron',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Daniel',
      email: 'dannegfer@alum.us.es',
      address: 'Avenida del Ejército, nº 1. Sevilla.',
      telephone: '677543432',
      optional_photo: null,
    },
    {
      id: 6,
      user_name: 'jesusHernandez',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Jesús',
      email: 'jesherdom1@alum.us.es',
      address: 'Avenida del Rocio, nº 123. Sevilla.',
      telephone: '691876543',
      optional_photo: null,
    },
    // moderator
    {
      id: 7,
      user_name: 'rosaSanchez',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Rosa',
      email: 'rosasanchez@gmail.com',
      address: 'Calle del Deporte, nº 8. Sevilla.',
      telephone: '785194638',
      optional_photo: null,
    },
    {
      id: 8,
      user_name: 'luciaMontero',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: false,
      name: 'Lucía',
      email: 'luciamontero@gmail.com',
      address: 'Calle del Amor, nº 45. Sevilla.',
      telephone: '824965327',
      optional_photo: null,
    },
    {
      id: 9,
      user_name: 'christianM',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Christian',
      email: 'chrmarand@alum.us.es',
      address: 'Avenida de Reina Mercedes, nº 34. Sevilla.',
      telephone: '765285432',
      optional_photo: 'http://www.ejemplo9.com/',
    },
    // particular
    {
      id: 10,
      user_name: 'palina',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a', // hola
      role: 'particular',
      activate: true,
      name: 'Palina',
      email: 'palina_lokaziouk@outlook.es',
      address: 'Avenida Blas Infante, nº 23. Sevilla.',
      telephone: '665823954',
      optional_photo: null,
    },
    {
      id: 11,
      user_name: 'alvarLuciana',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Luciana',
      email: 'alvar.luciana@gmail.com',
      address: 'Calle de la Paz, nº 56. Sevilla.',
      telephone: '696869357',
      optional_photo: null,
    },
    {
      id: 12,
      user_name: 'pidonado',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Pidonado',
      email: 'pidonado@agrosavia.com',
      address: 'Calle el Pinar, nº 23. Sevilla.',
      telephone: '954767889',
      optional_photo: null,
    },
    {
      id: 13,
      user_name: 'pablodmzeta',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Pablo',
      email: 'pablodmzeta@gmail.com',
      address: 'Avenida de la Palmera, nº 32. Sevilla.',
      telephone: '668523694',
      optional_photo: null,
    },
    {
      id: 14,
      user_name: 'aliciaps',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Alicia',
      email: 'aliciaps21998@gmail.com',
      address: 'Calle el País, nº 76. Sevilla',
      telephone: '678523694',
      optional_photo: null,
    },
    {
      id: 15,
      user_name: 'luciGali',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Lucía',
      email: 'lucigali37@gmail.com',
      address: 'Calle Trajano, nº 12. Sevilla.',
      telephone: '621523694',
      optional_photo: null,
    },
    {
      id: 16,
      user_name: 'belen.bmas',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Belén',
      email: 'belen.bmas@gmail.com',
      address: 'Calle Cuna, nº 18. Sevilla.',
      telephone: '688523694',
      optional_photo: null,
    },
    {
      id: 17,
      user_name: 'sacaLaCamara',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'La Cámara',
      email: 'sacalacamarablog@gmail.com',
      address: 'Calle Sol, nº 4. Sevilla.',
      telephone: '688523694',
      optional_photo: null,
    },
    {
      id: 18,
      user_name: 'mgarciacase',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'María',
      email: 'mgarciacase@gmail.com',
      address: 'Calle Blanco White, nº 21. Sevilla.',
      telephone: '698523694',
      optional_photo: null,
    },
    {
      id: 19,
      user_name: 'mariafvallejo',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'María',
      email: 'mariafvallejo@hotmail.com',
      address: 'Calle Gonzalo Bilbao',
      telephone: '678521194',
      optional_photo: null,
    },
    {
      id: 20,
      user_name: 'mcarmen',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'María del Carmen',
      email: 'mcarmen@gmail.com',
      address: 'Calle Lictores',
      telephone: '657527794',
      optional_photo: null,
    },
    {
      id: 21,
      user_name: 'juanEsp',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: false,
      name: 'Juan',
      email: 'juanesp@gmail.com',
      address: 'Calle Arroyo, nº 1. Sevilla.',
      telephone: '684223694',
      optional_photo: null,
    },
    {
      id: 22,
      user_name: 'clauCabanillas',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Claudia',
      email: 'claucabanillas@gmail.com',
      address: 'Calle Los Álamos, nº 1. Sevilla.',
      telephone: '632986423',
      optional_photo: null,
    },
    {
      id: 23,
      user_name: 'mariaRueda',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'María Rueda',
      email: 'mariacirca@gmail.com',
      address: 'Calle del Ron, nº 1. Sevilla.',
      telephone: '676876879',
      optional_photo: null,
    },
    {
      id: 24,
      user_name: 'candelaRueda',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Candela',
      email: 'candelaestrella@gmail.com',
      address: 'Calle La Estrella, nº 67. Sevilla.',
      telephone: '668523694',
      optional_photo: null,
    },
    {
      id: 25,
      user_name: 'estrellasabel',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Estrella',
      email: 'estrellasabel@gmail.com',
      address: 'Calle de La Candelaria, nº 23. Sevilla.',
      telephone: '698513614',
      optional_photo: null,
    },
    {
      id: 26,
      user_name: 'alfonsoAM',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Alfonso',
      email: 'alfonsoalfonsomarin@gmail.com',
      address: 'Calle la fuga, nº 6. Sevilla.',
      telephone: '677523692',
      optional_photo: null,
    },
    {
      id: 27,
      user_name: 'leticiaGavira',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Leticia',
      email: 'letigavira@gmail.com',
      address: 'Calle del Triunfo, nº 33. Sevilla.',
      telephone: '678753129',
      optional_photo: null,
    },
    {
      id: 28,
      user_name: 'nereaOrtiz',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Nerea',
      email: 'nereaortiz@gmail.com',
      address: 'Calle Santa María, nº 22. Sevilla.',
      telephone: '687435647',
      optional_photo: null,
    },
    {
      id: 29,
      user_name: 'azaharaOrtiz',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Azahara',
      email: 'azaharaortiz@gmail.com',
      address: 'Calle Don Juan, nº 1. Sevilla.',
      telephone: '687523694',
      optional_photo: null,
    },
    {
      id: 30,
      user_name: 'mariaIsabel',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Maria Isabel',
      email: 'mdiazoliva@gmail.com',
      address: 'Calle la Pereza, nº 22. Sevilla.',
      telephone: '675886758',
      optional_photo: null,
    },
    {
      id: 31,
      user_name: 'mariAtortosa',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'María Antonia',
      email: 'tonidominguez@gmail.com',
      address: 'Calle Tharsis, nº 1. Sevilla.',
      telephone: '678523114',
      optional_photo: null,
    },
    {
      id: 32,
      user_name: 'hugoGonzalez',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Hugo',
      email: 'hugogonzalez@gmail.com',
      address: 'Avenida de la Solea, nº 2. Sevilla.',
      telephone: '667723634',
      optional_photo: null,
    },
    {
      id: 33,
      user_name: 'andreaGo',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo33',
      email: 'ejemplo33@gmail.com',
      address: 'Calle ejemplo 33',
      telephone: '658987885',
      optional_photo: null,
    },
    {
      id: 34,
      user_name: 'evalan',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Eva',
      email: 'evalan@gmail.com',
      address: 'Calle Tesalónica, nº 1. Sevilla',
      telephone: '648523394',
      optional_photo: null,
    },
    // moderator
    {
      id: 35,
      user_name: 'paulaRey',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Paula',
      email: 'paulareymartin@gmail.com',
      address: 'Calle de la ada, nº 87. Sevilla.',
      telephone: '632523543',
      optional_photo: null,
    },
    {
      id: 36,
      user_name: 'juanValencia',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: false,
      name: 'Juan',
      email: 'juanvalencia@gmail.com',
      address: 'Calle Socorro, nº 36. Sevilla.',
      telephone: '654567696',
      optional_photo: null,
    },
    {
      id: 37,
      user_name: 'victorSar',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Victor',
      email: 'victorsarento@gmail.com',
      address: 'Calle del Bosque, nº 12. Sevilla.',
      telephone: '608523600',
      optional_photo: null,
    },
    {
      id: 38,
      user_name: 'estherExp',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Esther',
      email: 'estherexp@gmail.com',
      address: 'Calle las Encínas, nº 15. Sevilla.',
      telephone: '675849302',
      optional_photo: null,
    },
    {
      id: 39,
      user_name: 'miguelBer',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: false,
      name: 'Miguel',
      email: 'miguelberbe@gmail.com',
      address: 'Avenida de Miraflores, nº 4. Sevilla.',
      telephone: '675574822',
      optional_photo: null,
    },
    {
      id: 40,
      user_name: 'javierpm',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Javier',
      email: 'javierpm@gmail.com',
      address: 'Calle de la Luz, nº 8. Sevilla.',
      telephone: '611523696',
      optional_photo: null,
    },
    {
      id: 41,
      user_name: 'Pedro',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Pedro',
      email: 'pedrodraw@gmail.com',
      address: 'Calle Pablo de Rojas n1 41, Sevilla.',
      telephone: '611521196',
      optional_photo: null,
    },
    {
      // adoption
      id: 42,
      user_name: 'prodeanse',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Prodeanse',
      email: 'prodeanse@gmail.com',
      address: 'Calle Pirineos nº 42, Sevilla.',
      telephone: '675887980',
      optional_photo: null,
    },
    {
      id: 43,
      user_name: 'mastercat',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'mastercat',
      email: 'mastercat@gmail.com',
      address: 'Calle Rico Cejudo nº 43, Sevilla.',
      telephone: '611561196',
      optional_photo: null,
    },
    {
      id: 44,
      user_name: 'prodoggy',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'prodoggy',
      email: 'prodoggy@gmail.com',
      address: 'Calle Joaquin Cortés nº 44, Sevilla.',
      telephone: '954521197',
      optional_photo: null,
    },
    {
      id: 45,
      user_name: 'gatosamor',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Gatosamor',
      email: 'gatosamor@gmail.com',
      address: 'Calle Tarragona nº 45, Sevilla.',
      telephone: '954521197',
      optional_photo: null,
    },
    {
      id: 46,
      user_name: 'perrosConPasion',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Perros con Pasión',
      email: 'perrosconpasion@gmail.com',
      address: 'Calle Julio Verne nº 46, Sevilla.',
      telephone: '955521197',
      optional_photo: null,
    },
    {
      id: 47,
      user_name: 'arcaDeNoe',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Arca de Noe',
      email: 'arcadenoe@gmail.com',
      address: 'Calle los Rosales nº 47, Sevilla.',
      telephone: '954521197',
      optional_photo: null,
    },
    {
      id: 48,
      user_name: 'perrosPaCasa',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Perros para Casa',
      email: 'perrospacasa@gmail.com',
      address: 'Calle Azorín 48',
      telephone: '955526197',
      optional_photo: null,
    },
    {
      id: 49,
      user_name: 'loveanimals',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: false,
      name: 'LoveAnimals',
      email: 'loveanimals@gmail.com',
      address: 'Calle Montellana nº 49, Sevilla.',
      telephone: '954653212',
      optional_photo: null,
    },
    {
      id: 50,
      user_name: 'tuCompañero',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: false,
      name: 'Tu Compañero',
      email: 'tucompaniero@gmail.com',
      address: 'Calle Chopín nº 50, Sevilla.',
      telephone: '654521197',
      optional_photo: null,
    },
    {
      id: 51,
      user_name: 'protectoraMairena',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Protectora Mairena',
      email: 'protectoramairena@gmail.com',
      address: 'Calle Galileo nº 51, Sevilla.',
      telephone: '654521107',
      optional_photo: null,
    },
    {
      id: 52,
      user_name: 'protectoraTomares',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Protectora Tomares',
      email: 'protectoratomares@gmail.com',
      address: 'Calle Cicerón nº 52. Sevilla.',
      telephone: '652521107',
      optional_photo: null,
    },
    {
      id: 53,
      user_name: 'protectoraBormujos',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Protectora Bormujos',
      email: 'ejemplo53@gmail.com',
      address: 'Avenida de Almargen nº 106, Sevilla.',
      telephone: '955656657',
      optional_photo: null,
    },
    {
      id: 54,
      user_name: 'protectoraPM',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Protectora Pino Montano',
      email: 'protectorapinomontano@gmail.com',
      address: 'Avenida Doña Francisquita nº 54, Sevilla.',
      telephone: '652521130',
      optional_photo: null,
    },
    {
      id: 55,
      user_name: 'protectoraTriana',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Protectora Triana',
      email: 'protectoratriana@gmail.com',
      address: 'Calle Ortega Gasset nº 55, Sevilla.',
      telephone: '650021130',
      optional_photo: null,
    },
  ]);

  // administrator
  await knex('administrator').insert([
    {id: 1, surname: 'Cuevas', user_account_id: 4},
    {id: 2, surname: 'Negrón', user_account_id: 5},
    {id: 3, surname: 'Hernández', user_account_id: 6},
    {id: 4, surname: 'Pérez', user_account_id: 20},
    {id: 5, surname: 'Espina', user_account_id: 21},
    {id: 6, surname: 'Cabanillas', user_account_id: 22},
    {id: 7, surname: 'Rueda', user_account_id: 23},
    {id: 8, surname: 'Rueda', user_account_id: 24},
  ]);

  // particular
  await knex('particular').insert([
    {
      id: 1,
      surname: 'Palina',
      user_account_id: 10,
    },
    {
      id: 2,
      surname: 'Luciana',
      user_account_id: 11,
    },
    {
      id: 3,
      surname: 'Pidonado',
      user_account_id: 12,
    },
    {
      id: 4,
      surname: 'Mzeta',
      user_account_id: 13,
    },
    {
      id: 5,
      surname: 'Ps',
      user_account_id: 14,
    },
    {
      id: 6,
      surname: 'Galí',
      user_account_id: 15,
    },
    {
      id: 7,
      surname: 'Bmas',
      user_account_id: 16,
    },
    {
      id: 8,
      surname: 'Cámara',
      user_account_id: 17,
    },
    {
      id: 9,
      surname: 'García',
      user_account_id: 18,
    },
    {
      id: 10,
      surname: 'Vallejo',
      user_account_id: 19,
    },
    {
      id: 11,
      surname: 'Estrella',
      user_account_id: 25,
    },
    {
      id: 12,
      surname: 'Alfonso',
      user_account_id: 26,
    },
    {
      id: 13,
      surname: 'Gavira',
      user_account_id: 27,
    },
    {
      id: 14,
      surname: 'Ortíz',
      user_account_id: 28,
    },
    {
      id: 15,
      surname: 'Ortíz',
      user_account_id: 29,
    },
    {
      id: 16,
      surname: 'Diaz',
      user_account_id: 30,
    },
    {
      id: 17,
      surname: 'Domínguez',
      user_account_id: 31,
    },
    {
      id: 18,
      surname: 'González',
      user_account_id: 32,
    },
    {
      id: 19,
      surname: 'Gómez',
      user_account_id: 33,
    },
    {
      id: 20,
      surname: 'Castro',
      user_account_id: 34,
    },
  ]);

  // publication
  await knex('publication').insert([
    // breeding
    {
      id: 1,
      animal_photo:
        'images/animal_photos/doberman.jpg, images/animal_photos/doberman2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2020-01-01',
      genre: 'Male',
      breed: 'Doberman',
      transaction_status: 'In progress',
      type: 'Dog',
      location: 'Calle Jabugo nº 1, Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 2,

      animal_photo:
        'images/animal_photos/bulterrier.jpg, images/animal_photos/bulterrier2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2015-06-30',
      genre: 'Female',
      breed: 'Bulldog Terrier',
      transaction_status: 'Completed',
      type: 'Dog',
      location: 'Calle Arroyo nº 3, Sevilla.',
      pedigree: true,
      particular_id: 2,
    },
    {
      id: 3,
      animal_photo:
        'images/animal_photos/yorkshire.jpg, images/animal_photos/yorkshire2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2018-09-24',
      genre: 'Male',
      breed: 'Yorkshire Terrier',
      transaction_status: 'Completed',
      type: 'Dog',
      location: 'Calle Castellar nº 3, Sevilla.',
      pedigree: true,
      particular_id: 3,
    },

    // adoption
    {
      id: 4,
      animal_photo:
        'images/animal_photos/maine.jpg, images/animal_photos/maine2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2018-11-15',
      genre: 'Male',
      breed: 'Maine Coon',
      transaction_status: 'Offered',
      type: 'Cat',
      location: 'Calle Clavellinas nº 4, Sevilla.',
      pedigree: false,
      particular_id: 4,
    },
    {
      id: 5,
      animal_photo:
        'images/animal_photos/siames.jpg, images/animal_photos/siames2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2019-12-01',
      genre: 'Female',
      breed: 'Siamés',
      transaction_status: 'In progress',
      type: 'Cat',
      location: 'Avda. ejemplo, 5',
      pedigree: true,
      particular_id: 5,
    },
    {
      id: 6,
      animal_photo:
        'images/animal_photos/caballoarabe.jpg, images/animal_photos/caballoarabe2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2015-08-23',
      genre: 'Male',
      breed: 'Árabe',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle Laraña nº 5, Sevilla.',
      pedigree: true,
      particular_id: 6,
    },
    {
      id: 7,
      animal_photo:
        'images/animal_photos/caballoarabe.jpg, images/animal_photos/caballoarabe2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2016-12-12',
      genre: 'Female',
      breed: 'Árabe',
      transaction_status: 'Completed',
      type: 'Horse',
      location: 'Calle Imagen nº 7, Sevilla.',
      pedigree: true,
      particular_id: 7,
    },
    {
      id: 8,
      animal_photo:
        'images/animal_photos/caballoandaluz.jpg, images/animal_photos/caballoandaluz2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2015-07-07',
      genre: 'Female',
      breed: 'Andaluz',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle Rioja nº 7, Sevilla.',
      pedigree: true,
      particular_id: 8,
    },
    {
      id: 9,
      animal_photo:
        'images/animal_photos/mustang.jpg, images/animal_photos/mustang2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2017-11-03',
      genre: 'Male',
      breed: 'Mustang',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle Rocío nº 8, Sevilla.',
      pedigree: true,
      particular_id: 9,
    },
    {
      id: 10,
      animal_photo:
        'images/animal_photos/yorkshire.jpg, images/animal_photos/yorkshire2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2018-11-04',
      genre: 'Male',
      breed: 'Yorkshire',
      transaction_status: 'In progress',
      type: 'Dog',
      location: 'Calle Pureza nº 11, Sevilla.',
      pedigree: true,
      particular_id: 10,
    },
    {
      id: 11,
      animal_photo:
        'images/animal_photos/husky.jpg, images/animal_photos/husky2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2013-02-04',
      genre: 'Male',
      breed: 'Husky siberiano',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Alfarería nº 12, Sevilla.',
      pedigree: true,
      particular_id: 11,
    },
    {
      id: 12,
      animal_photo:
        'images/animal_photos/brabante.jpg, images/animal_photos/brabante2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2013-12-04',
      genre: 'Male',
      breed: 'Brabante',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle Manuel Arellano nº 3, Sevilla.',
      pedigree: true,
      particular_id: 12,
    },
    {
      id: 13,
      animal_photo:
        'images/animal_photos/caballo-islandes.jpg, images/animal_photos/caballo-islandes2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2015-12-04',
      genre: 'Male',
      breed: 'Islandés',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle Niculoso Pisano nº 2, Sevilla.',
      pedigree: false,
      particular_id: 13,
    },
    {
      id: 14,
      animal_photo:
        'images/animal_photos/caballotrakehner.jpg, images/animal_photos/caballotrakehner2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2010-10-06',
      genre: 'Male',
      breed: 'Trakehner',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle Arnao de Flandes nº 12. Sevilla.',
      pedigree: true,
      particular_id: 14,
    },
    {
      id: 15,
      animal_photo:
        'images/animal_photos/caballoandaluz.jpg, images/animal_photos/caballoandaluz2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2012-10-02',
      genre: 'Female',
      breed: 'Andalúz',
      transaction_status: 'In progress',
      type: 'Horse',
      location: 'Calle San Vicente de Paul nº 9, Sevilla.',
      pedigree: true,
      particular_id: 15,
    },
    {
      id: 16,
      animal_photo:
        'images/animal_photos/pomerania.jpg, images/animal_photos/pomerania2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2012-10-09',
      genre: 'Male',
      breed: 'Pomerania',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Avda. de Coria nº 25, Sevilla.',
      pedigree: true,
      particular_id: 16,
    },
    {
      id: 17,
      animal_photo:
        'images/animal_photos/caballoandaluz.jpg, images/animal_photos/caballoandaluz2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2011-11-01',
      genre: 'Male',
      breed: 'Andalúz',
      transaction_status: 'Offered',
      type: 'Horse',
      location: 'Calle José León nº 30, Sevilla.',
      pedigree: true,
      particular_id: 17,
    },
    {
      id: 18,
      animal_photo:
        'images/animal_photos/yorkshire.jpg, images/animal_photos/yorkshire2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2019-12-04',
      genre: 'Male',
      breed: 'Yorkshire',
      transaction_status: 'Completed',
      type: 'Dog',
      location: 'Calle María Ortíz nº 12, Sevilla.',
      pedigree: false,
      particular_id: 18,
    },
    {
      id: 19,
      animal_photo:
        'images/animal_photos/siames.jpg, images/animal_photos/siames2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2013-10-09',
      genre: 'Female',
      breed: 'siames',
      transaction_status: 'In progress',
      type: 'Cat',
      location: 'Calle Juan Díaz de Solís nº 19, Sevilla.',
      pedigree: true,
      particular_id: 19,
    },
    {
      id: 20,
      animal_photo:
        'images/animal_photos/bulterrier.jpg, images/animal_photos/bulterrier2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2013-06-03',
      genre: 'Female',
      breed: 'Bulldog',
      transaction_status: 'Completed',
      type: 'Dog',
      location: 'Calle Rubén Darío nº 12. Sevilla.',
      pedigree: true,
      particular_id: 20,
    },
    {
      id: 21,
      animal_photo:
        'images/animal_photos/bullterrier.jpg, images/animal_photos/bulterrier2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2019-01-01',
      genre: 'Male',
      breed: 'Bulldog',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Samuel Morse nº 21. Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 22,
      animal_photo:
        'images/animal_photos/yorkshire.jpg, images/animal_photos/yorkshire2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2016-04-06',
      genre: 'Female',
      breed: 'Yorkshire',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Tarso nº 10, Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 23,
      animal_photo:
        'images/animal_photos/caniche.jpg, images/animal_photos/caniche2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2017-12-06',
      genre: 'Female',
      breed: 'Caniche',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle la Petenera nº 23. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 24,
      animal_photo:
        'images/animal_photos/pastor_aleman.jpg, images/animal_photos/pastor_aleman2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2014-10-04',
      genre: 'Male',
      breed: 'Pastor Alemán',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Nufro Sánchez nº 24. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 25,
      animal_photo:
        'images/animal_photos/pastor_aleman.jpg, images/animal_photos/pastor_aleman2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2010-04-12',
      genre: 'Male',
      breed: 'Pastor Alemán',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Antonio Gala nº 25. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 26,
      animal_photo:
        'images/animal_photos/husky.jpg, images/animal_photos/husky2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2013-02-27',
      genre: 'Female',
      breed: 'Husky siberiano',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Virgen de la Guía nº 26. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 27,
      animal_photo:
        'images/animal_photos/pomerania.jpg, images/animal_photos/pomerania2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2015-12-10',
      genre: 'Male',
      breed: 'Pomerania',
      transaction_status: 'In progress',
      type: 'Dog',
      location: 'Calle Juan Núñez nº 27, Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 28,
      animal_photo:
        'images/animal_photos/pomerania.jpg, images/animal_photos/pomerania2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2009-07-09',
      genre: 'Male',
      breed: 'Pomerania',
      transaction_status: 'Completed',
      type: 'Dog',
      location: 'Calle Aznalfarache nº 28. Sevilla.',
      pedigree: false,
      particular_id: null,
    },
    {
      id: 29,
      animal_photo:
        'images/animal_photos/rottweiler.jpg, images/animal_photos/rottweiler2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2011-04-04',
      genre: 'Male',
      breed: 'Rottweiler',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Antonio Pantión nº 4. Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 30,
      animal_photo:
        'images/animal_photos/husky.jpg, images/animal_photos/husky2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'In revision',
      birth_date: '2013-02-27',
      genre: 'Female',
      breed: 'Husky siberiano',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Virgen de la Guía nº 26. Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 31,
      animal_photo:
        'images/animal_photos/rottweiler.jpg, images/animal_photos/rottweiler2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'In revision',
      birth_date: '2013-11-05',
      genre: 'Male',
      breed: 'Rottweiler',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Antonio Pantión nº 4. Sevilla.',
      pedigree: true,
      particular_id: 2,
    },
    {
      id: 32,
      animal_photo:
        'images/animal_photos/rottweiler.jpg, images/animal_photos/rottweiler2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'In revision',
      birth_date: '2010-07-24',
      genre: 'Male',
      breed: 'Rottweiler',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Antonio Pantión nº 4. Sevilla.',
      pedigree: true,
      particular_id: 3,
    },
    {
      id: 33,
      animal_photo:
        'images/animal_photos/pomerania.jpg, images/animal_photos/pomerania2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'In revision',
      birth_date: '2018-02-03',
      genre: 'Male',
      breed: 'Pomerania',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Juan Núñez nº 27, Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 34,
      animal_photo:
        'images/animal_photos/caniche.jpg, images/animal_photos/caniche2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2017-12-06',
      genre: 'Female',
      breed: 'Caniche',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle la Petenera nº 23. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 35,
      animal_photo:
        'images/animal_photos/pastor_aleman.jpg, images/animal_photos/pastor_aleman2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2014-10-04',
      genre: 'Male',
      breed: 'Pastor Alemán',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Nufro Sánchez nº 24. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 36,
      animal_photo:
        'images/animal_photos/pastor_aleman.jpg, images/animal_photos/pastor_aleman2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2010-04-12',
      genre: 'Male',
      breed: 'Pastor Alemán',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Antonio Gala nº 25. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 37,
      animal_photo:
        'images/animal_photos/husky.jpg, images/animal_photos/husky2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2013-02-27',
      genre: 'Female',
      breed: 'Husky siberiano',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Virgen de la Guía nº 26. Sevilla.',
      pedigree: true,
      particular_id: null,
    },
    {
      id: 38,
      animal_photo:
        'images/animal_photos/pomerania.jpg, images/animal_photos/pomerania2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2015-12-10',
      genre: 'Male',
      breed: 'Pomerania',
      transaction_status: 'In progress',
      type: 'Dog',
      location: 'Calle Juan Núñez nº 27, Sevilla.',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 39,
      animal_photo:
        'images/animal_photos/pomerania.jpg, images/animal_photos/pomerania2.jpg',
      identification_photo: 'images/identification_photos/PERROPORTE.jpg',
      vaccine_passport: 'images/vaccine_passports/vaccine.jpg',
      document_status: 'Accepted',
      birth_date: '2009-07-09',
      genre: 'Male',
      breed: 'Pomerania',
      transaction_status: 'Offered',
      type: 'Dog',
      location: 'Calle Aznalfarache nº 28. Sevilla.',
      pedigree: false,
      particular_id: 1,
    },
  ]);

  // request
  await knex('request').insert([
    {
      id: 1,
      status: 'Accepted',
      publication_id: 3,
      particular_id: 1,
    },
    {
      id: 2,
      status: 'Rejected',
      publication_id: 1,
      particular_id: 2,
    },
    {
      id: 3,
      status: 'Accepted',
      publication_id: 2,
      particular_id: 3,
    },
    {
      id: 4,
      status: 'Rejected',
      publication_id: 6,
      particular_id: 4,
    },
    {
      id: 5,
      status: 'Accepted',
      publication_id: 5,
      particular_id: 6,
    },
    {
      id: 6,
      status: 'Accepted',
      publication_id: 7,
      particular_id: 4,
    },
    {
      id: 7,
      status: 'Accepted',
      publication_id: 8,
      particular_id: 12,
    },
    {
      id: 8,
      status: 'Rejected',
      publication_id: 9,
      particular_id: 16,
    },
    {
      id: 9,
      status: 'Accepted',
      publication_id: 10,
      particular_id: 8,
    },
    {
      id: 10,
      status: 'Pending',
      publication_id: 11,
      particular_id: 12,
    },
    {
      id: 11,
      status: 'Accepted',
      publication_id: 12,
      particular_id: 4,
    },
    {
      id: 12,
      status: 'Accepted',
      publication_id: 13,
      particular_id: 2,
    },
    {
      id: 13,
      status: 'Accepted',
      publication_id: 14,
      particular_id: 15,
    },
    {
      id: 14,
      status: 'Rejected',
      publication_id: 15,
      particular_id: 17,
    },
    {
      id: 15,
      status: 'Pending',
      publication_id: 16,
      particular_id: 13,
    },
    {
      id: 16,
      status: 'Pending',
      publication_id: 17,
      particular_id: 14,
    },
    {
      id: 17,
      status: 'Accepted',
      publication_id: 18,
      particular_id: 9,
    },
    {
      id: 18,
      status: 'Accepted',
      publication_id: 19,
      particular_id: 4,
    },
    {
      id: 19,
      status: 'Accepted',
      publication_id: 20,
      particular_id: 18,
    },
    {
      id: 20,
      status: 'Rejected',
      publication_id: 14,
      particular_id: 13,
    },
    {
      id: 21,
      status: 'Rejected',
      publication_id: 8,
      particular_id: 14,
    },
    {
      id: 22,
      status: 'Rejected',
      publication_id: 4,
      particular_id: 9,
    },
    {
      id: 23,
      status: 'Rejected',
      publication_id: 12,
      particular_id: 4,
    },
    {
      id: 24,
      status: 'Rejected',
      publication_id: 17,
      particular_id: 18,
    },
    {
      id: 25,
      status: 'Rejected',
      publication_id: 4,
      particular_id: 1,
    },
    {
      id: 26,
      status: 'Rejected',
      publication_id: 2,
      particular_id: 1,
    },
    {
      id: 27,
      status: 'Rejected',
      publication_id: 7,
      particular_id: 5,
    },
    {
      id: 28,
      status: 'Rejected',
      publication_id: 5,
      particular_id: 1,
    },
    {
      id: 29,
      status: 'Rejected',
      publication_id: 7,
      particular_id: 1,
    },
    {
      id: 30,
      status: 'Accepted',
      publication_id: 6,
      particular_id: 1,
    },
    {
      id: 31,
      status: 'Accepted',
      publication_id: 9,
      particular_id: 1,
    },
    {
      id: 32,
      status: 'Accepted',
      publication_id: 15,
      particular_id: 1,
    },
    {
      id: 33,
      status: 'Pending',
      publication_id: 17,
      particular_id: 1,
    },
    {
      id: 34,
      status: 'Rejected',
      publication_id: 1,
      particular_id: 15,
    },
    {
      id: 35,
      status: 'Accepted',
      publication_id: 1,
      particular_id: 8,
    },
    {
      id: 36,
      status: 'Rejected',
      publication_id: 1,
      particular_id: 12,
    },
    {
      id: 37,
      status: 'Rejected',
      publication_id: 1,
      particular_id: 4,
    },
    {
      id: 38,
      status: 'Rejected',
      publication_id: 38,
      particular_id: 15,
    },
    {
      id: 39,
      status: 'Accepted',
      publication_id: 38,
      particular_id: 8,
    },
    {
      id: 40,
      status: 'Rejected',
      publication_id: 38,
      particular_id: 12,
    },
    {
      id: 41,
      status: 'Rejected',
      publication_id: 38,
      particular_id: 4,
    },
    {
      id: 42,
      status: 'Accepted',
      publication_id: 27,
      particular_id: 1,
    },
    {
      id: 43,
      status: 'Accepted',
      publication_id: 28,
      particular_id: 1,
    },
    {
      id: 44,
      status: 'Pending',
      publication_id: 29,
      particular_id: 1,
    },
    {
      id: 45,
      status: 'Rejected',
      publication_id: 28,
      particular_id: 1,
    },
    {
      id: 46,
      status: 'Pending',
      publication_id: 4,
      particular_id: 1,
    },
  ]);

  // review

  await knex('review').insert([
    {
      id: 1,
      star: 5,
      review_description: 'La crianza fue completada con éxito.',
      publication_id: 18,
      particular_id: 9,
    },
    {
      id: 2,
      star: 5,
      review_description: 'La crianza fue completada con éxito.',
      publication_id: 20,
      particular_id: 18,
    },
  ]);

  // moderator
  await knex('moderator').insert([
    {id: 1, surname: 'Sánchez', user_account_id: 7},
    {id: 2, surname: 'Montero', user_account_id: 8},
    {id: 3, surname: 'Martínez', user_account_id: 9},
    {id: 4, surname: 'Rey', user_account_id: 35},
    {id: 5, surname: 'Valencia', user_account_id: 36},
    {id: 6, surname: 'Sarento', user_account_id: 37},
    {id: 7, surname: 'Expósito', user_account_id: 38},
    {id: 8, surname: 'Berbe', user_account_id: 39},
    {id: 9, surname: 'PM', user_account_id: 40},
    {id: 10, surname: 'Rojas', user_account_id: 41},
  ]);

  // breeding
  await knex('breeding').insert([
    {id: 1, codenumber: 'abcd1234', price: 5.5, publication_id: 1},
    {id: 2, codenumber: 'abcs1234', price: 69, publication_id: 2},
    {id: 3, codenumber: 'abcd1214', price: 44.1, publication_id: 3},
    {id: 4, codenumber: 'ddcd1234', price: 23.5, publication_id: 4},
    {id: 5, codenumber: 'abcddd34', price: 45.8, publication_id: 5},
    {id: 6, codenumber: 'abcd12ss', price: 50, publication_id: 6},
    {id: 7, codenumber: 'abcdwq34', price: 87, publication_id: 7},
    {id: 8, codenumber: 'abcd3434', price: 30, publication_id: 8},
    {id: 9, codenumber: 'abcd1666', price: 45, publication_id: 9},
    {id: 10, codenumber: 'abcd1994', price: 56, publication_id: 10},
    {id: 11, codenumber: 'a4r51234', price: 106, publication_id: 11},
    {id: 12, codenumber: 'abc7u734', price: 36, publication_id: 12},
    {id: 13, codenumber: 'ab3e4234', price: 22, publication_id: 13},
    {id: 14, codenumber: 'a8091234', price: 65, publication_id: 14},
    {id: 15, codenumber: 'a1231234', price: 61, publication_id: 15},
    {id: 16, codenumber: 'abc89074', price: 21, publication_id: 16},
    {id: 17, codenumber: 'abc68974', price: 55, publication_id: 17},
    {id: 18, codenumber: 'a1e4r234', price: 61, publication_id: 18},
    {id: 19, codenumber: 'abcdiko9', price: 21, publication_id: 19},
    {id: 20, codenumber: 'abc3e7u4', price: 55, publication_id: 20},
    {id: 21, codenumber: 'abc4y7u4', price: 105, publication_id: 29},
    {id: 22, codenumber: 'abcdol98', price: 50, publication_id: 30},
    {id: 23, codenumber: 'ab5j12g4', price: 39, publication_id: 31},
    {id: 24, codenumber: 'abcd7654', price: 45, publication_id: 32},
    {id: 25, codenumber: 'thukd1234', price: 75, publication_id: 33},
  ]);

  // shelter
  await knex('shelter').insert([
    {id: 1, user_account_id: 1},
    {id: 2, user_account_id: 2},
    {id: 3, user_account_id: 3},
    {id: 4, user_account_id: 42},
    {id: 5, user_account_id: 43},
    {id: 6, user_account_id: 44},
    {id: 7, user_account_id: 45},
    {id: 8, user_account_id: 46},
    {id: 9, user_account_id: 47},
    {id: 10, user_account_id: 48},
    {id: 11, user_account_id: 49},
    {id: 12, user_account_id: 50},
    {id: 13, user_account_id: 51},
    {id: 14, user_account_id: 52},
    {id: 15, user_account_id: 53},
    {id: 16, user_account_id: 54},
    {id: 17, user_account_id: 55},
  ]);

  // adoption
  await knex('adoption').insert([
    {
      id: 1,
      name: 'Niko',
      taxes: 390,
      publication_id: 21,
      shelter_id: null,
    },
    {
      id: 2,
      name: 'Kiwi',
      taxes: 210,
      publication_id: 25,
      shelter_id: 2,
    },
    {
      id: 3,
      name: 'Sebas',
      taxes: 870,
      publication_id: 26,
      shelter_id: 3,
    },
    {
      id: 4,
      name: 'Star',
      taxes: 70,
      publication_id: 27,
      shelter_id: 10,
    },
    {
      id: 5,
      name: 'Rox',
      taxes: 500,
      publication_id: 28,
      shelter_id: 11,
    },
    {
      id: 6,
      name: 'kiko',
      taxes: 345,
      publication_id: 22,
      shelter_id: 8,
    },
    {
      id: 7,
      name: 'Jess',
      taxes: 567,
      publication_id: 23,
      shelter_id: 4,
    },
    {
      id: 8,
      name: 'Tos',
      taxes: 789,
      publication_id: 24,
      shelter_id: 7,
    },
    {
      id: 9,
      name: 'Fox',
      taxes: 100,
      publication_id: 34,
      shelter_id: 1,
    },
    {
      id: 10,
      name: 'Niko',
      taxes: 120,
      publication_id: 35,
      shelter_id: 1,
    },
    {
      id: 11,
      name: 'Rango',
      taxes: 80,
      publication_id: 36,
      shelter_id: 1,
    },
    {
      id: 12,
      name: 'Cattie',
      taxes: 50,
      publication_id: 37,
      shelter_id: 2,
    },
    {
      id: 13,
      name: 'Peter',
      taxes: 75,
      publication_id: 38,
      shelter_id: null,
    },
    {
      id: 14,
      name: 'Parker',
      taxes: 49,
      publication_id: 39,
      shelter_id: null,
    },
  ]);

  // vet
  await knex('vet').insert([
    {
      id: 1,
      name: 'Centro Veterinario',
      surname: 'Bormujos',
      email: 'info@centroveterinariobormujos.com',
      url: 'https://centroveterinariobormujos.com',
      address: 'Av. del Aljarafe, 68, 41930 Bormujos, Sevilla.',
      telephone: '955725684',
      optional_photo:
        'https://fastly.4sqi.net/img/general/600x600/33362540_7Ib17cahmEjREuHkg9_h1bisn1GFn5Pyd-2rVtq2qzw.jpg',
      is_premium: true,
    },
    {
      id: 2,
      name: 'La Huella',
      surname: 'Bormujos',
      email: 'info@veterinarioslahuella.es',
      url: 'http://veterinarioslahuella.es/clinica-veterinaria-bormujos/',
      address: 'Calle Jacinto Benavente, 2C, 41930 Bormujos, Sevilla.',
      telephone: '955723761',
      optional_photo:
        'https://lh3.googleusercontent.com/P4s80SY2nURV-wmx2M-uack9j8neJoZnITBEwWAD892NUt5UP_ZZLEd9QqOhXFmwZnsRFQHkNw=w1080-h608-p-no-v0',
      is_premium: false,
    },
    {
      id: 3,
      name: 'Mascodín',
      surname: 'Animales De Compañía Sevilla',
      email: 'mascodinsevilla@gmail.com',
      url: 'http://www.clubmascodin.com',
      address: 'Calle Diseño, 4, 41927 Mairena del Aljarafe, Sevilla.',
      telephone: '955089393',
      optional_photo: 'images/vets/mascodin.png',
      is_premium: false,
    },
    {
      id: 4,
      name: 'Clínica Veterinaria Fernando',
      surname: 'Palomo',
      email: 'cvfpr@hotmail.com',
      url: null,
      address: 'Calle Aceituna, 3, 41960 Gines, Sevilla.',
      telephone: '954714547',
      optional_photo:
        'https://2.bp.blogspot.com/_dq4LEWcxxRU/SxGGMhnozzI/AAAAAAAAAVc/UwUeWf_uRLw/s1600/clinica+veterinaria+f+palomo.jpg',
      is_premium: true,
    },
    {
      id: 5,
      name: 'Catdog',
      surname: 'Veterinario',
      email: 'catdoggines@gmail.com',
      url:
        'http://catdog.es/nuestras-clinicas-veterinarias-aljarafe/clinica-veterinaria-gines-aljarafe/',
      address: 'Calle la Mogaba, 15, 41960 Gines, Sevilla.',
      telephone: '954717300',
      optional_photo:
        'https://lh3.googleusercontent.com/proxy/br_RwwK4_LOaO0eI-8m--kTMf5Gb5t4RjQaBNDwW4_9nPUEfoSUXk6OpXHFpB7xwA2Df1trhamBTLcGqsGY6CA6w7DfHTaoOpXnDrNyGQ7prtABRvZKVxdCoUscd1Q',
      is_premium: false,
    },
    {
      id: 6,
      name: 'Clínica Veterinaria Tartessos',
      surname: 'Veterinario',
      email: 'tartessos@gmail.com',
      url: null,
      address:
        'Calle Virgen de Loreto, 11, 41950 Castilleja de la Cuesta, Sevilla.',
      telephone: '954162152',
      optional_photo: 'images/vets/tartessos.jpg',
      is_premium: true,
    },
    {
      id: 7,
      name: 'SERVIMASCOTAS LOYMA',
      surname: 'Veterinario',
      email: 'servimascotasloywa@gmail.com',
      url: 'https://www.facebook.com/servimascotasloyma',
      address: 'Calle Majuelo, 6, 41960 Gines, Sevilla.',
      telephone: '954717888',
      optional_photo: null,
      is_premium: false,
    },
    {
      id: 8,
      name: 'HISPALVET VETERINARIOS',
      surname: 'Veterinario',
      email: 'hispalvet@gmail.com',
      url: 'http://www.hispalvet.com',
      address: 'Calle José Luis Navarro, 14, 41940 Tomares, Sevilla.',
      telephone: '954044835',
      optional_photo:
        'https://t2.ea.ltmcdn.com/es/places/6/7/0/img_7076_clinica-veterinaria-san-bernardo_0_300_150.jpg',
      is_premium: false,
    },
    {
      id: 9,
      name: 'Clínica Veterinaria Santa Rita',
      surname: 'Veterinario',
      email: 'santarica@gmail.com',
      url: 'https://www.facebook.com/clinicaveterinariasantaritatomares',
      address: 'C/ Tomás De Ibarra, 24, 41940 Tomares, Sevilla.',
      telephone: '954151279',
      optional_photo:
        'https://s3-media0.fl.yelpcdn.com/bphoto/Rh2CTWTKc5L9cs5qWHtdzQ/o.jpg',
      is_premium: true,
    },
    {
      id: 10,
      name: 'Centro Veterinario San Germán',
      surname: 'Veterinario',
      email: 'sangerman@gmail.com',
      url: 'https://www.facebook.com/sangermanvet/',
      address: 'Calle Clara Campoamor, 74, 41940 Tomares, Sevilla.',
      telephone: '954154836',
      optional_photo: null,
      is_premium: false,
    },
    {
      id: 11,
      name: 'Hospital Veterinario 24h Mascotasalud',
      surname: 'Veterinario',
      email: 'mascotasalud@gmail.com',
      url: 'https://www.mascotasalud.com',
      address: 'Av. de la Arboleda, 40, 41940 Tomares, Sevilla.',
      telephone: '954870057',
      optional_photo:
        'https://www.mascotasalud.com/s/cc_images/teaserbox_33684667.jpg?t=1529350544',
      is_premium: false,
    },
    {
      id: 12,
      name: 'CLINICA VETERINARIA VETALYS SAN JUAN',
      surname: 'Veterinario',
      email: 'vetalusanjuan@gmail.com',
      url: 'http://vetalysveterinarios.com',
      address:
        'Calle Rodríguez Marín, 67, 41920 San Juan de Aznalfarache, Sevilla.',
      telephone: '954760813',
      optional_photo:
        'https://vetalysveterinarios.com/wp-content/uploads/2016/05/clinica_sevilla.jpg',
      is_premium: true,
    },
    {
      id: 13,
      name: 'Centro Veterinario Triana',
      surname: 'Veterinario',
      email: 'trianavet@gmail.com',
      url: 'https://www.centroveterinariotriana.es/es/',
      address: 'Calle San Jacinto, 68, 41010 Sevilla.',
      telephone: '954333472',
      optional_photo:
        'https://s3-media0.fl.yelpcdn.com/bphoto/MwcPd94wJJQZXkkI98rWgg/l.jpg',
      is_premium: true,
    },
    {
      id: 14,
      name: 'VETERINARIA ALAMEDA SEVILLA',
      surname: 'Veterinario',
      email: 'alamedasevillavet@gmail.com',
      url: 'https://www.veterinariaalameda.com',
      address: 'Alameda de Hércules, 41, 41002 Sevilla.',
      telephone: '954378569',
      optional_photo:
        'https://www.mundoanimalia.com/images/veterinario/76/7b/92/9831384e2ed3938f00b8fb98b3424649/fotos_070__5773.jpg',
      is_premium: false,
    },
    {
      id: 15,
      name: 'Clínica Veterinaria Ronda de Capuchinos',
      surname: 'Veterinario',
      email: 'rondadecapuchinosvet@gmail.com',
      url: null,
      address: 'Ronda de Capuchinos, 4, 41003 Sevilla.',
      telephone: '954537535',
      optional_photo: null,
      is_premium: true,
    },
    {
      id: 16,
      name: 'THE DOGTOR CLINICA VETERINARIA',
      surname: 'Veterinario',
      email: 'thedogtor@gmail.com',
      url: 'https://www.thedogtorvet.com',
      address: 'Calle Juan de Mata Carriazo, 5, Local 3, 41018 Sevilla.',
      telephone: '954410900',
      optional_photo:
        'https://lh3.googleusercontent.com/proxy/ukNTpmPkphSMptwOQ74CFlLkgjVQ5DM7aKIuF0pXnia84BNpUx76yRh5wfXFpmEDhIRZ0hgjxGHwJ7Gr0LnnfwSKUldZkHq2n-yM73qMsWY',
      is_premium: false,
    },
    {
      id: 17,
      name: 'Tamarguillo Veterinaria',
      surname: 'Veterinario',
      email: 'tamarguillovet@gmail.com',
      url: 'https://www.centroveterinariotamarguillo.com',
      address: 'Calle Nalón, 19, 41005 Sevilla.',
      telephone: '954922075',
      optional_photo:
        'https://t1.ea.ltmcdn.com/es/places/9/7/0/img_7079_centro-veterinario-tamarguillo_0_orig.jpg',
      is_premium: true,
    },
  ]);
};
