exports.seed = async (knex) => {
  // Deletes ALL existing entries
  await knex('shelter').del();
  await knex('adoption').del();
  await knex('administrator').del();
  await knex('breeding').del();
  await knex('request').del();
  await knex('publication').del();
  await knex('particular').del();
  await knex('moderator').del();
  await knex('vet').del();
  await knex('user_account').del();

  // user_account
  await knex('user_account').insert([
    // shelter
    {
      id: 1,
      user_name: 'ejemplo1',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a', // hola
      role: 'shelter',
      activate: true,
      name: 'Ejemplo1',
      email_adress: 'ejemplo1@gmail.com',
      adress: 'Calle ejemplo 1',
      telephone: '954695241',
      optional_photo: 'http://www.ejemplo1.com/',
    },
    {
      id: 2,
      user_name: 'ejemplo2',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo2',
      email_adress: 'ejemplo2@gmail.com',
      adress: 'Calle ejemplo 2',
      telephone: '954478512',
      optional_photo: null,
    },
    {
      id: 3,
      user_name: 'ejemplo3',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: false,
      name: 'Ejemplo3',
      email_adress: 'ejemplo3@gmail.com',
      adress: 'Calle ejemplo 3',
      telephone: '954896523',
      optional_photo: 'http://www.ejemplo3.com/',
    },
    // administrator
    {
      id: 4,
      user_name: 'ejemplo4',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo4',
      email_adress: 'ejemplo4@gmail.com',
      adress: 'Calle ejemplo 4',
      telephone: '541236987',
      optional_photo: 'http://www.ejemplo4.com/',
    },
    {
      id: 5,
      user_name: 'ejemplo5',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo5',
      email_adress: 'ejemplo5@gmail.com',
      adress: 'Calle ejemplo 5',
      telephone: '458963258',
      optional_photo: null,
    },
    {
      id: 6,
      user_name: 'ejemplo6',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: false,
      name: 'Ejemplo6',
      email_adress: 'ejemplo6@gmail.com',
      adress: 'Calle ejemplo 6',
      telephone: '496327851',
      optional_photo: 'http://www.ejemplo6.com/',
    },
    // moderator
    {
      id: 7,
      user_name: 'ejemplo7',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo7',
      email_adress: 'ejemplo7@gmail.com',
      adress: 'Calle ejemplo 7',
      telephone: '785194638',
      optional_photo: 'http://www.ejemplo7.com/',
    },
    {
      id: 8,
      user_name: 'ejemplo8',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo8',
      email_adress: 'ejemplo8@gmail.com',
      adress: 'Calle ejemplo 8',
      telephone: '824965327',
      optional_photo: null,
    },
    {
      id: 9,
      user_name: 'ejemplo9',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: false,
      name: 'Ejemplo9',
      email_adress: 'ejemplo9@gmail.com',
      adress: 'Calle ejemplo 9',
      telephone: '765285432',
      optional_photo: 'http://www.ejemplo9.com/',
    },
    // particular
    {
      id: 10,
      user_name: 'ejemplo10',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a', // hola
      role: 'particular',
      activate: true,
      name: 'Ejemplo10',
      email_adress: 'ejemplo10@gmail.com',
      adress: 'Calle ejemplo 10',
      telephone: '765823954',
      optional_photo: 'http://www.ejemplo10.com/',
    },
    {
      id: 11,
      user_name: 'ejemplo11',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo11',
      email_adress: 'ejemplo11@gmail.com',
      adress: 'Calle ejemplo 11',
      telephone: '496869357',
      optional_photo: null,
    },
    {
      id: 12,
      user_name: 'ejemplo12',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo12',
      email_adress: 'ejemplo12@gmail.com',
      adress: 'Calle ejemplo 12',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo12.com/',
    },
    {
      id: 13,
      user_name: 'ejemplo13',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo13',
      email_adress: 'ejemplo13@gmail.com',
      adress: 'Calle ejemplo 13',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo13.com/',
    },
    {
      id: 14,
      user_name: 'ejemplo14',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo14',
      email_adress: 'ejemplo14@gmail.com',
      adress: 'Calle ejemplo 14',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo14.com/',
    },
    {
      id: 15,
      user_name: 'ejemplo15',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo13',
      email_adress: 'ejemplo15@gmail.com',
      adress: 'Calle ejemplo 15',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo15.com/',
    },
    {
      id: 16,
      user_name: 'ejemplo16',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo16',
      email_adress: 'ejemplo16@gmail.com',
      adress: 'Calle ejemplo 16',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo16.com/',
    },
    {
      id: 17,
      user_name: 'ejemplo17',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo17',
      email_adress: 'ejemplo17@gmail.com',
      adress: 'Calle ejemplo 17',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo17.com/',
    },
    {
      id: 18,
      user_name: 'ejemplo18',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo18',
      email_adress: 'ejemplo18@gmail.com',
      adress: 'Calle ejemplo 18',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo18.com/',
    },
    {
      id: 19,
      user_name: 'ejemplo19',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo19',
      email_adress: 'ejemplo19@gmail.com',
      adress: 'Calle ejemplo 19',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo19.com/',
    },
    {
      id: 20,
      user_name: 'ejemplo20',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo20',
      email_adress: 'ejemplo20@gmail.com',
      adress: 'Calle ejemplo 20',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo20.com/',
    },
    {
      id: 21,
      user_name: 'ejemplo21',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo21',
      email_adress: 'ejemplo21@gmail.com',
      adress: 'Calle ejemplo 21',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo21.com/',
    },
    {
      id: 22,
      user_name: 'ejemplo22',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo22',
      email_adress: 'ejemplo22@gmail.com',
      adress: 'Calle ejemplo 22',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo22.com/',
    },
    {
      id: 23,
      user_name: 'ejemplo23',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo23',
      email_adress: 'ejemplo23@gmail.com',
      adress: 'Calle ejemplo 23',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo23.com/',
    },
    {
      id: 24,
      user_name: 'ejemplo24',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'administrator',
      activate: true,
      name: 'Ejemplo24',
      email_adress: 'ejemplo24@gmail.com',
      adress: 'Calle ejemplo 24',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo24.com/',
    },
    {
      id: 25,
      user_name: 'ejemplo25',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo25',
      email_adress: 'ejemplo25@gmail.com',
      adress: 'Calle ejemplo 25',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo25.com/',
    },
    {
      id: 26,
      user_name: 'ejemplo26',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo26',
      email_adress: 'ejemplo26@gmail.com',
      adress: 'Calle ejemplo 26',
      telephone: '178523692',
      optional_photo: 'http://www.ejemplo26.com/',
    },
    {
      id: 27,
      user_name: 'ejemplo27',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo27',
      email_adress: 'ejemplo27@gmail.com',
      adress: 'Calle ejemplo 27',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo27.com/',
    },
    {
      id: 28,
      user_name: 'ejemplo28',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo28',
      email_adress: 'ejemplo28@gmail.com',
      adress: 'Calle ejemplo 28',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo28.com/',
    },
    {
      id: 29,
      user_name: 'ejemplo29',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo29',
      email_adress: 'ejemplo29@gmail.com',
      adress: 'Calle ejemplo 29',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo29.com/',
    },
    {
      id: 30,
      user_name: 'ejemplo30',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo30',
      email_adress: 'ejemplo30@gmail.com',
      adress: 'Calle ejemplo 30',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo30.com/',
    },
    {
      id: 31,
      user_name: 'ejemplo31',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: false,
      name: 'Ejemplo30',
      email_adress: 'ejemplo31@gmail.com',
      adress: 'Calle ejemplo 31',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo30.com/',
    },
    {
      id: 32,
      user_name: 'ejemplo32',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo32',
      email_adress: 'ejemplo32@gmail.com',
      adress: 'Calle ejemplo 32',
      telephone: '178523634',
      optional_photo: 'http://www.ejemplo32.com/',
    },
    {
      id: 33,
      user_name: 'ejemplo33',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo33',
      email_adress: 'ejemplo33@gmail.com',
      adress: 'Calle ejemplo 33',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo33.com/',
    },
    {
      id: 34,
      user_name: 'ejemplo34',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'particular',
      activate: true,
      name: 'Ejemplo34',
      email_adress: 'ejemplo34@gmail.com',
      adress: 'Calle ejemplo 34',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo34.com/',
    },
    {
      id: 35,
      user_name: 'ejemplo35',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo35',
      email_adress: 'ejemplo35@gmail.com',
      adress: 'Calle ejemplo 35',
      telephone: '178523694',
      optional_photo: 'http://www.ejemplo35.com/',
    },
    {
      id: 36,
      user_name: 'ejemplo36',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo36',
      email_adress: 'ejemplo36@gmail.com',
      adress: 'Calle ejemplo 36',
      telephone: '178523696',
      optional_photo: 'http://www.ejemplo36.com/',
    },
    {
      id: 37,
      user_name: 'ejemplo37',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo37',
      email_adress: 'ejemplo37@gmail.com',
      adress: 'Calle ejemplo 37',
      telephone: '178523622',
      optional_photo: 'http://www.ejemplo37.com/',
    },
    {
      id: 38,
      user_name: 'ejemplo38',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo38',
      email_adress: 'ejemplo38@gmail.com',
      adress: 'Calle ejemplo 38',
      telephone: '178513696',
      optional_photo: 'http://www.ejemplo38.com/',
    },
    {
      id: 39,
      user_name: 'ejemplo39',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo39',
      email_adress: 'ejemplo39@gmail.com',
      adress: 'Calle ejemplo 39',
      telephone: '178523699',
      optional_photo: 'http://www.ejemplo39.com/',
    },
    {
      id: 40,
      user_name: 'ejemplo40',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo40',
      email_adress: 'ejemplo40@gmail.com',
      adress: 'Calle ejemplo 40',
      telephone: '111523696',
      optional_photo: 'http://www.ejemplo40.com/',
    },
    {
      id: 41,
      user_name: 'ejemplo41',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'moderator',
      activate: true,
      name: 'Ejemplo41',
      email_adress: 'ejemplo41@gmail.com',
      adress: 'Calle ejemplo 41',
      telephone: '111521196',
      optional_photo: 'http://www.ejemplo41.com/',
    },
    {
      id: 42,
      user_name: 'ejemplo42',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo42',
      email_adress: 'ejemplo42@gmail.com',
      adress: 'Calle ejemplo 42',
      telephone: '111521197',
      optional_photo: 'http://www.ejemplo42.com/',
    },
    {
      id: 43,
      user_name: 'ejemplo43',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo43',
      email_adress: 'ejemplo43@gmail.com',
      adress: 'Calle ejemplo 43',
      telephone: '111521193',
      optional_photo: 'http://www.ejemplo43.com/',
    },
    {
      id: 44,
      user_name: 'ejemplo44',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo44',
      email_adress: 'ejemplo44@gmail.com',
      adress: 'Calle ejemplo 44',
      telephone: '111521197',
      optional_photo: 'http://www.ejemplo44.com/',
    },
    {
      id: 45,
      user_name: 'ejemplo45',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo45',
      email_adress: 'ejemplo45@gmail.com',
      adress: 'Calle ejemplo 45',
      telephone: '222521197',
      optional_photo: 'http://www.ejemplo45.com/',
    },
    {
      id: 46,
      user_name: 'ejemplo46',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo46',
      email_adress: 'ejemplo46@gmail.com',
      adress: 'Calle ejemplo 46',
      telephone: '111521197',
      optional_photo: 'http://www.ejemplo46.com/',
    },
    {
      id: 47,
      user_name: 'ejemplo47',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo47',
      email_adress: 'ejemplo47@gmail.com',
      adress: 'Calle ejemplo 47',
      telephone: '513521197',
      optional_photo: 'http://www.ejemplo47.com/',
    },
    {
      id: 48,
      user_name: 'ejemplo48',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo48',
      email_adress: 'ejemplo48@gmail.com',
      adress: 'Calle ejemplo 48',
      telephone: '111526197',
      optional_photo: 'http://www.ejemplo48.com/',
    },
    {
      id: 49,
      user_name: 'ejemplo49',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo49',
      email_adress: 'ejemplo49@gmail.com',
      adress: 'Calle ejemplo 49',
      telephone: '166521197',
      optional_photo: 'http://www.ejemplo49.com/',
    },
    {
      id: 50,
      user_name: 'ejemplo50',
      password: '$2a$10$aSCoNvSmUKhs8jfzuzf/Gu9t53AsXwlUbE3ZCR/n2wTcJPupBjL4a',
      role: 'shelter',
      activate: true,
      name: 'Ejemplo50',
      email_adress: 'ejemplo50@gmail.com',
      adress: 'Calle ejemplo 50',
      telephone: '654521197',
      optional_photo: 'http://www.ejemplo50.com/',
    },
  ]);

  // administrator
  await knex('administrator').insert([
    {id: 1, surname: 'Ejemplo 4', user_account_id: 4},
    {id: 2, surname: 'Ejemplo 5', user_account_id: 5},
    {id: 3, surname: 'Ejemplo 6', user_account_id: 6},
    {id: 4, surname: 'Ejemplo 7', user_account_id: 20},
    {id: 5, surname: 'Ejemplo 8', user_account_id: 21},
    {id: 6, surname: 'Ejemplo 9', user_account_id: 22},
    {id: 7, surname: 'Ejemplo 9', user_account_id: 23},
    {id: 8, surname: 'Ejemplo 10', user_account_id: 24},
  ]);

  // particular
  await knex('particular').insert([
    {
      id: 1,
      surname: 'surname1',
      user_account_id: 10,
    },
    {
      id: 2,
      surname: 'surname2',
      user_account_id: 11,
    },
    {
      id: 3,
      surname: 'surname3',
      user_account_id: 12,
    },
    {
      id: 4,
      surname: 'surname4',
      user_account_id: 13,
    },
    {
      id: 5,
      surname: 'surname5',
      user_account_id: 14,
    },
    {
      id: 6,
      surname: 'surname6',
      user_account_id: 15,
    },
    {
      id: 7,
      surname: 'surname44',
      user_account_id: 16,
    },
    {
      id: 8,
      surname: 'surname23',
      user_account_id: 17,
    },
    {
      id: 9,
      surname: 'surname76',
      user_account_id: 18,
    },
    {
      id: 10,
      surname: 'surname44',
      user_account_id: 19,
    },
    {
      id: 11,
      surname: 'surname7',
      user_account_id: 25,
    },
    {
      id: 12,
      surname: 'surname8',
      user_account_id: 26,
    },
    {
      id: 13,
      surname: 'surname9',
      user_account_id: 27,
    },
    {
      id: 14,
      surname: 'surname10',
      user_account_id: 28,
    },
    {
      id: 15,
      surname: 'surname12',
      user_account_id: 29,
    },
    {
      id: 16,
      surname: 'surname13',
      user_account_id: 30,
    },
    {
      id: 17,
      surname: 'surname15',
      user_account_id: 31,
    },
    {
      id: 18,
      surname: 'surname16',
      user_account_id: 32,
    },
    {
      id: 19,
      surname: 'surname17',
      user_account_id: 33,
    },
    {
      id: 20,
      surname: 'surname18',
      user_account_id: 34,
    },
  ]);

  // publication
  await knex('publication').insert([
    // breeding
    {
      id: 1,
      animal_photo: 'http://www.ejemplo1.com/, http://www.ejemplo2.com/',
      identification_photo: 'http://www.ejemplo1.com/',
      vaccine_passport: 'http://www.ejemplo1.com/',
      document_status: 'Accepted',
      age: 8,
      genre: 'Male',
      breed: 'Doberman',
      transaction_status: 'In progress',
      title: 'Example breeding 1',
      type: 'Dog',
      location: 'Avda. ejemplo, 1',
      pedigree: true,
      particular_id: 1,
    },
    {
      id: 2,
      animal_photo: 'http://www.ejemplo3.com/',
      identification_photo: 'http://www.ejemplo2.com/',
      vaccine_passport: 'http://www.ejemplo2.com/',
      document_status: 'In revision',
      age: 3,
      genre: 'Female',
      breed: 'Bulldog Terrier',
      transaction_status: 'Completed',
      title: 'Example breeding 2',
      type: 'Dog',
      location: 'Avda. ejemplo, 2',
      pedigree: true,
      particular_id: 2,
    },
    {
      id: 3,
      animal_photo:
        'http://www.ejemplo4.com/, http://www.ejemplo5.com/, http://www.ejemplo6.com/',
      identification_photo: 'http://www.ejemplo3.com/',
      vaccine_passport: 'http://www.ejemplo3.com/',
      document_status: 'Rejected',
      age: 5,
      genre: 'Male',
      breed: 'Yorkshire Terrier',
      transaction_status: 'In progress',
      title: 'Example breeding 3',
      type: 'Dog',
      location: 'Avda. ejemplo, 3',
      pedigree: true,
      particular_id: 3,
    },

    // adoption
    {
      id: 4,
      animal_photo: 'http://www.ejemplo5.com/, http://www.ejemplo8.com/',
      identification_photo: 'http://www.ejemplo4.com/',
      vaccine_passport: 'http://www.ejemplo4.com/',
      document_status: 'Accepted',
      age: 6,
      genre: 'Male',
      breed: 'Maine Coon',
      transaction_status: 'Completed',
      title: 'Example adoption 1',
      type: 'Cat',
      location: 'Avda. ejemplo, 4',
      pedigree: false,
      particular_id: 4,
    },
    {
      id: 5,
      animal_photo: 'http://www.ejemplo7.com/',
      identification_photo: 'http://www.ejemplo5.com/',
      vaccine_passport: 'http://www.ejemplo5.com/',
      document_status: 'Accepted',
      age: 8,
      genre: 'Female',
      breed: 'Siamés',
      transaction_status: 'In progress',
      title: 'Example adoption 2',
      type: 'Cat',
      location: 'Avda. ejemplo, 5',
      pedigree: true,
      particular_id: 5,
    },
    {
      id: 6,
      animal_photo:
        'http://www.ejemplo9.com/, http://www.ejemplo1.com/, http://www.ejemplo2.com/',
      identification_photo: 'http://www.ejemplo6.com/',
      vaccine_passport: 'http://www.ejemplo6.com/',
      document_status: 'Accepted',
      age: 2,
      genre: 'Male',
      breed: 'Árabe',
      transaction_status: 'In progress',
      title: 'Example adoption 3',
      type: 'Horse',
      location: 'Avda. ejemplo, 6',
      pedigree: true,
      particular_id: 6,
    },
    {
      id: 7,
      animal_photo:
        'http://www.ejemplo10.com/, http://www.ejemplo33.com/, http://www.ejemplo21.com/',
      identification_photo: 'http://www.ejemplo7.com/',
      vaccine_passport: 'http://www.ejemplo7.com/',
      document_status: 'Accepted',
      age: 2,
      genre: 'Female',
      breed: 'Árabe',
      transaction_status: 'In progress',
      title: 'Example adoption 4',
      type: 'Horse',
      location: 'Avda. ejemplo, 7',
      pedigree: true,
      particular_id: 7,
    },
    {
      id: 8,
      animal_photo:
        'http://www.ejemplo11.com/, http://www.ejemplo34.com/, http://www.ejemplo22.com/',
      identification_photo: 'http://www.ejemplo8.com/',
      vaccine_passport: 'http://www.ejemplo8.com/',
      document_status: 'Accepted',
      age: 6,
      genre: 'Female',
      breed: 'Andaluz',
      transaction_status: 'In progress',
      title: 'Example adoption 10',
      type: 'Horse',
      location: 'Avda. ejemplo, 8',
      pedigree: true,
      particular_id: 8,
    },
    {
      id: 9,
      animal_photo:
        'http://www.ejemplo13.com/, http://www.ejemplo35.com/, http://www.ejemplo24.com/',
      identification_photo: 'http://www.ejemplo9.com/',
      vaccine_passport: 'http://www.ejemplo9.com/',
      document_status: 'Accepted',
      age: 1,
      genre: 'Male',
      breed: 'Mustang',
      transaction_status: 'In progress',
      title: 'Example adoption 6',
      type: 'Horse',
      location: 'Avda. ejemplo, 9',
      pedigree: true,
      particular_id: 9,
    },
    {
      id: 10,
      animal_photo:
        'http://www.ejemplo14.com/, http://www.ejemplo36.com/, http://www.ejemplo25.com/',
      identification_photo: 'http://www.ejemplo10.com/',
      vaccine_passport: 'http://www.ejemplo10.com/',
      document_status: 'Accepted',
      age: 3,
      genre: 'Male',
      breed: 'Yorkshire',
      transaction_status: 'In progress',
      title: 'Example adoption 11',
      type: 'Dog',
      location: 'Avda. ejemplo, 11',
      pedigree: true,
      particular_id: 10,
    },
    {
      id: 11,
      animal_photo:
        'http://www.ejemplo15.com/, http://www.ejemplo37.com/, http://www.ejemplo26.com/',
      identification_photo: 'http://www.ejemplo11.com/',
      vaccine_passport: 'http://www.ejemplo11.com/',
      document_status: 'Accepted',
      age: 4,
      genre: 'Male',
      breed: 'Husky siberiano',
      transaction_status: 'In progress',
      title: 'Example adoption 12',
      type: 'Dog',
      location: 'Avda. ejemplo, 12',
      pedigree: true,
      particular_id: 11,
    },
    {
      id: 12,
      animal_photo:
        'http://www.ejemplo16.com/, http://www.ejemplo37.com/, http://www.ejemplo26.com/',
      identification_photo: 'http://www.ejemplo12.com/',
      vaccine_passport: 'http://www.ejemplo12.com/',
      document_status: 'Accepted',
      age: 4,
      genre: 'Male',
      breed: 'Brabante',
      transaction_status: 'In progress',
      title: 'Example adoption 12',
      type: 'Horse',
      location: 'Avda. ejemplo, 12',
      pedigree: true,
      particular_id: 12,
    },
    {
      id: 13,
      animal_photo:
        'http://www.ejemplo17.com/, http://www.ejemplo38.com/, http://www.ejemplo27.com/',
      identification_photo: 'http://www.ejemplo13.com/',
      vaccine_passport: 'http://www.ejemplo13.com/',
      document_status: 'Accepted',
      age: 2,
      genre: 'Male',
      breed: 'Islandés',
      transaction_status: 'In progress',
      title: 'Example adoption 13',
      type: 'Horse',
      location: 'Avda. ejemplo, 13',
      pedigree: false,
      particular_id: 13,
    },
    {
      id: 14,
      animal_photo:
        'http://www.ejemplo18.com/, http://www.ejemplo39.com/, http://www.ejemplo28.com/',
      identification_photo: 'http://www.ejemplo14.com/',
      vaccine_passport: 'http://www.ejemplo14.com/',
      document_status: 'Accepted',
      age: 2,
      genre: 'Male',
      breed: 'Trakehner',
      transaction_status: 'In progress',
      title: 'Example adoption 14',
      type: 'Horse',
      location: 'Avda. ejemplo, 14',
      pedigree: true,
      particular_id: 14,
    },
    {
      id: 15,
      animal_photo:
        'http://www.ejemplo19.com/, http://www.ejemplo40.com/, http://www.ejemplo29.com/',
      identification_photo: 'http://www.ejemplo15.com/',
      vaccine_passport: 'http://www.ejemplo15.com/',
      document_status: 'Accepted',
      age: 5,
      genre: 'Female',
      breed: 'Andalúz',
      transaction_status: 'In progress',
      title: 'Example adoption 15',
      type: 'Horse',
      location: 'Avda. ejemplo, 16',
      pedigree: true,
      particular_id: 15,
    },
    {
      id: 16,
      animal_photo:
        'http://www.ejemplo20.com/, http://www.ejemplo41.com/, http://www.ejemplo30.com/',
      identification_photo: 'http://www.ejemplo16.com/',
      vaccine_passport: 'http://www.ejemplo16.com/',
      document_status: 'Accepted',
      age: 3,
      genre: 'Male',
      breed: 'Nórico',
      transaction_status: 'In progress',
      title: 'Example adoption 15',
      type: 'Horse',
      location: 'Avda. ejemplo, 15',
      pedigree: true,
      particular_id: 16,
    },
    {
      id: 17,
      animal_photo:
        'http://www.ejemplo56.com/, http://www.ejemplo45.com/, http://www.ejemplo62.com/',
      identification_photo: 'http://www.ejemplo17.com/',
      vaccine_passport: 'http://www.ejemplo17.com/',
      document_status: 'Accepted',
      age: 3,
      genre: 'Male',
      breed: 'Nórico',
      transaction_status: 'In progress',
      title: 'Example adoption 17',
      type: 'Horse',
      location: 'Avda. ejemplo, 17',
      pedigree: true,
      particular_id: 17,
    },
    {
      id: 18,
      animal_photo:
        'http://www.ejemplo57.com/, http://www.ejemplo76.com/, http://www.ejemplo544.com/',
      identification_photo: 'http://www.ejemplo18.com/',
      vaccine_passport: 'http://www.ejemplo18.com/',
      document_status: 'Accepted',
      age: 8,
      genre: 'Male',
      breed: 'Lipizzano',
      transaction_status: 'In progress',
      title: 'Example adoption 18',
      type: 'Horse',
      location: 'Avda. ejemplo, 18',
      pedigree: false,
      particular_id: 18,
    },
    {
      id: 19,
      animal_photo:
        'http://www.ejemplo60.com/, http://www.ejemplo79.com/, http://www.ejemplo244.com/',
      identification_photo: 'http://www.ejemplo19.com/',
      vaccine_passport: 'http://www.ejemplo19.com/',
      document_status: 'Accepted',
      age: 4,
      genre: 'Female',
      breed: 'Lipizzano',
      transaction_status: 'In progress',
      title: 'Example adoption 19',
      type: 'Horse',
      location: 'Avda. ejemplo, 19',
      pedigree: true,
      particular_id: 19,
    },
    {
      id: 20,
      animal_photo:
        'http://www.ejemplo610.com/, http://www.ejemplo179.com/, http://www.ejemplo224.com/',
      identification_photo: 'http://www.ejemplo20.com/',
      vaccine_passport: 'http://www.ejemplo20.com/',
      document_status: 'Accepted',
      age: 4,
      genre: 'Female',
      breed: 'Bulldog',
      transaction_status: 'Completed',
      title: 'Example adoption 20',
      type: 'Dog',
      location: 'Avda. ejemplo, 20',
      pedigree: true,
      particular_id: 20,
    },
    {
      id: 21,
      animal_photo:
        'http://www.ejemplo610.com/, http://www.ejemplo179.com/, http://www.ejemplo224.com/',
      identification_photo: 'http://www.ejemplo20.com/',
      vaccine_passport: 'http://www.ejemplo20.com/',
      document_status: 'Accepted',
      age: 3,
      genre: 'Male',
      breed: 'Bulldog',
      transaction_status: 'Completed',
      title: 'Example adoption 21',
      type: 'Dog',
      location: 'Avda. ejemplo, 21',
      pedigree: true,
      particular_id: 20,
    },
    {
      id: 22,
      animal_photo:
        'http://www.ejemplo610.com/, http://www.ejemplo179.com/, http://www.ejemplo224.com/',
      identification_photo: 'http://www.ejemplo20.com/',
      vaccine_passport: 'http://www.ejemplo20.com/',
      document_status: 'Accepted',
      age: 2,
      genre: 'Female',
      breed: 'Yorkshire',
      transaction_status: 'In progress',
      title: 'Example adoption 22',
      type: 'Dog',
      location: 'Avda. ejemplo, 22',
      pedigree: true,
      particular_id: 20,
    },
    {
      id: 23,
      animal_photo:
        'http://www.ejemplo610.com/, http://www.ejemplo179.com/, http://www.ejemplo224.com/',
      identification_photo: 'http://www.ejemplo20.com/',
      vaccine_passport: 'http://www.ejemplo20.com/',
      document_status: 'Accepted',
      age: 4,
      genre: 'Female',
      breed: 'Caniche',
      transaction_status: 'Completed',
      title: 'Example adoption 23',
      type: 'Dog',
      location: 'Avda. ejemplo, 23',
      pedigree: true,
      particular_id: 20,
    },
    {
      id: 24,
      animal_photo:
        'http://www.ejemplo610.com/, http://www.ejemplo179.com/, http://www.ejemplo224.com/',
      identification_photo: 'http://www.ejemplo20.com/',
      vaccine_passport: 'http://www.ejemplo20.com/',
      document_status: 'Accepted',
      age: 6,
      genre: 'Male',
      breed: 'Pastor Alemán',
      transaction_status: 'Completed',
      title: 'Example adoption 24',
      type: 'Dog',
      location: 'Avda. ejemplo, 24',
      pedigree: true,
      particular_id: 20,
    },
  ]);

  // request
  await knex('request').insert([
    {
      id: 1,
      status: 'Favorite',
      is_favorite: true,
      publication_id: 3,
      particular_id: 1,
    },
    {
      id: 2,
      status: 'Pending',
      is_favorite: false,
      publication_id: 1,
      particular_id: 2,
    },
    {
      id: 3,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 2,
      particular_id: 3,
    },
    {
      id: 4,
      status: 'Favorite',
      is_favorite: true,
      publication_id: 6,
      particular_id: 1,
    },
    {
      id: 5,
      status: 'Pending',
      is_favorite: false,
      publication_id: 4,
      particular_id: 2,
    },
    {
      id: 6,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 5,
      particular_id: 3,
    },
    {
      id: 7,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 7,
      particular_id: 7,
    },
    {
      id: 8,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 8,
      particular_id: 8,
    },
    {
      id: 9,
      status: 'Favorite',
      is_favorite: true,
      publication_id: 9,
      particular_id: 9,
    },
    {
      id: 10,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 10,
      particular_id: 10,
    },
    {
      id: 11,
      status: 'Pending',
      is_favorite: true,
      publication_id: 11,
      particular_id: 11,
    },
    {
      id: 12,
      status: 'Accepted',
      is_favorite: true,
      publication_id: 12,
      particular_id: 12,
    },
    {
      id: 13,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 13,
      particular_id: 13,
    },
    {
      id: 14,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 14,
      particular_id: 14,
    },
    {
      id: 15,
      status: 'Pending',
      is_favorite: false,
      publication_id: 15,
      particular_id: 15,
    },
    {
      id: 16,
      status: 'Favorite',
      is_favorite: true,
      publication_id: 16,
      particular_id: 16,
    },
    {
      id: 17,
      status: 'Pending',
      is_favorite: false,
      publication_id: 17,
      particular_id: 17,
    },
    {
      id: 18,
      status: 'Accepted',
      is_favorite: true,
      publication_id: 18,
      particular_id: 18,
    },
    {
      id: 19,
      status: 'Accepted',
      is_favorite: false,
      publication_id: 19,
      particular_id: 19,
    },
    {
      id: 20,
      status: 'Accepted',
      is_favorite: true,
      publication_id: 20,
      particular_id: 20,
    },
  ]);

  // moderator
  await knex('moderator').insert([
    {id: 1, surname: 'surname1', user_account_id: 7},
    {id: 2, surname: 'surname2', user_account_id: 8},
    {id: 3, surname: 'surname3', user_account_id: 9},
    {id: 4, surname: 'surname4', user_account_id: 35},
    {id: 5, surname: 'surname5', user_account_id: 36},
    {id: 6, surname: 'surname6', user_account_id: 37},
    {id: 7, surname: 'surname7', user_account_id: 38},
    {id: 8, surname: 'surname8', user_account_id: 39},
    {id: 9, surname: 'surname9', user_account_id: 40},
    {id: 10, surname: 'surname10', user_account_id: 41},
  ]);

  // breeding
  await knex('breeding').insert([
    {id: 1, price: 5.5, publication_id: 1},
    {id: 2, price: 69, publication_id: 2},
    {id: 3, price: 44.1, publication_id: 3},
    {id: 4, price: 23.5, publication_id: 5},
    {id: 5, price: 45.8, publication_id: 6},
    {id: 6, price: 50, publication_id: 7},
    {id: 7, price: 87, publication_id: 8},
    {id: 8, price: 30, publication_id: 9},
    {id: 9, price: 45, publication_id: 10},
    {id: 10, price: 56, publication_id: 11},
    {id: 11, price: 106, publication_id: 12},
    {id: 12, price: 36, publication_id: 14},
    {id: 13, price: 22, publication_id: 15},
    {id: 14, price: 65, publication_id: 16},
    {id: 15, price: 61, publication_id: 17},
    {id: 16, price: 21, publication_id: 19},
    {id: 17, price: 55, publication_id: 20},
  ]);

  // shelter
  await knex('shelter').insert([
    {id: 1, user_account_id: 1},
    {id: 2, user_account_id: 2},
    {id: 3, user_account_id: 3},
    {id: 4, user_account_id: 42},
    {id: 5, user_account_id: 43},
    {id: 6, user_account_id: 44},
    {id: 7, user_account_id: 45},
    {id: 8, user_account_id: 46},
    {id: 9, user_account_id: 47},
    {id: 10, user_account_id: 48},
    {id: 11, user_account_id: 49},
    {id: 12, user_account_id: 50},
  ]);

  // adoption
  await knex('adoption').insert([
    {
      id: 1,
      name: 'Niko',
      taxes: 390,
      publication_id: 4,
      shelter_id: 1,
    },
    {
      id: 2,
      name: 'Kiwi',
      taxes: 210,
      publication_id: 5,
      shelter_id: 2,
    },
    {
      id: 3,
      name: 'Sebas',
      taxes: 870,
      publication_id: 6,
      shelter_id: 3,
    },
    {
      id: 4,
      name: 'Star',
      taxes: 70,
      publication_id: 10,
      shelter_id: 10,
    },
    {
      id: 5,
      name: 'Rox',
      taxes: 500,
      publication_id: 11,
      shelter_id: 11,
    },
    {
      id: 6,
      name: 'Pepito',
      taxes: 432,
      publication_id: 20,
      shelter_id: 9,
    },
    {
      id: 7,
      name: 'Tana',
      taxes: 123,
      publication_id: 21,
      shelter_id: 12,
    },
    {
      id: 8,
      name: 'kiko',
      taxes: 345,
      publication_id: 22,
      shelter_id: 8,
    },
    {
      id: 9,
      name: 'Jess',
      taxes: 567,
      publication_id: 23,
      shelter_id: 4,
    },
    {
      id: 10,
      name: 'Tos',
      taxes: 789,
      publication_id: 24,
      shelter_id: 7,
    },
  ]);

  // vet
  await knex('vet').insert([
    {
      id: 1,
      name: 'Ejemplo16',
      surname: 'Vet1',
      email_adress: 'ejemplo16@gmail.com',
      adress: 'Calle ejemplo 16',
      telephone: '751485326',
      optional_photo: 'http://www.ejemplo16.com/',
      is_premium: true,
    },
    {
      id: 2,
      name: 'Ejemplo17',
      surname: 'Vet2',
      email_adress: 'ejemplo17@gmail.com',
      adress: 'Calle ejemplo 17',
      telephone: '756318964',
      optional_photo: null,
      is_premium: false,
    },
    {
      id: 3,
      name: 'Ejemplo18',
      surname: 'Vet3',
      email_adress: 'ejemplo18@gmail.com',
      adress: 'Calle ejemplo 18',
      telephone: '486359625',
      optional_photo: 'http://www.ejemplo18.com/',
      is_premium: false,
    },
    {
      id: 4,
      name: 'Ejemplo144',
      surname: 'Vet4',
      email_adress: 'ejemplo20@gmail.com',
      adress: 'Calle ejemplo 20',
      telephone: '486351625',
      optional_photo: 'http://www.ejemplo21.com/',
      is_premium: true,
    },
    {
      id: 5,
      name: 'Ejemplo1833',
      surname: 'Vet5',
      email_adress: 'ejemplo21@gmail.com',
      adress: 'Calle ejemplo 22',
      telephone: '486359615',
      optional_photo: 'http://www.ejemplo20.com/',
      is_premium: false,
    },
    {
      id: 6,
      name: 'Ejemplo1433',
      surname: 'Vet6',
      email_adress: 'ejemplo213@gmail.com',
      adress: 'Calle ejemplo 2333',
      telephone: '486339635',
      optional_photo: 'http://www.ejemplo233.com/',
      is_premium: true,
    },
    {
      id: 7,
      name: 'Eje2mplo1833',
      surname: 'Vet7',
      email_adress: 'ejemplo221@gmail.com',
      adress: 'Calle ejemplo 233',
      telephone: '486359115',
      optional_photo: 'http://www.ejemplo222.com/',
      is_premium: false,
    },
    {
      id: 8,
      name: 'Ejemplo11833',
      surname: 'Vet8',
      email_adress: 'ejemplo27@gmail.com',
      adress: 'Calle ejemplo 244',
      telephone: '486111615',
      optional_photo: 'http://www.ejemplo22.com/',
      is_premium: false,
    },
    {
      id: 9,
      name: 'Ejemplo2833',
      surname: 'Vet9',
      email_adress: 'ejemplo29@gmail.com',
      adress: 'Calle ejemplo 29',
      telephone: '486359115',
      optional_photo: 'http://www.ejemplo29.com/',
      is_premium: true,
    },
    {
      id: 10,
      name: 'Ejemplo1133',
      surname: 'Vet10',
      email_adress: 'ejemplo266@gmail.com',
      adress: 'Calle ejemplo 245',
      telephone: '486359612',
      optional_photo: 'http://www.ejemplo256.com/',
      is_premium: false,
    },
    {
      id: 11,
      name: 'Ejemplo1836',
      surname: 'Vet11',
      email_adress: 'ejemplo2111@gmail.com',
      adress: 'Calle ejemplo 221',
      telephone: '486559615',
      optional_photo: 'http://www.ejemplo2022.com/',
      is_premium: false,
    },
    {
      id: 12,
      name: 'Ejemplo11833',
      surname: 'Vet12',
      email_adress: 'ejemplo211@gmail.com',
      adress: 'Calle ejemplo 122',
      telephone: '416339616',
      optional_photo: 'http://www.ejemplo201.com/',
      is_premium: true,
    },
    {
      id: 13,
      name: 'Ejemplo6833',
      surname: 'Vet13',
      email_adress: 'ejemplo121@gmail.com',
      adress: 'Calle ejemplo 4322',
      telephone: '486359666',
      optional_photo: 'http://www.ejemplo720.com/',
      is_premium: true,
    },
    {
      id: 14,
      name: 'Ejemplo1533',
      surname: 'Vet15',
      email_adress: 'ejemplo1432@gmail.com',
      adress: 'Calle ejemplo 2231',
      telephone: '416159543',
      optional_photo: 'http://www.ejemplo276.com/',
      is_premium: false,
    },
    {
      id: 15,
      name: 'Ejemplo1883',
      surname: 'Vet15',
      email_adress: 'ejemplo1111@gmail.com',
      adress: 'Calle ejemplo 234',
      telephone: '486356435',
      optional_photo: 'http://www.ejemplo210.com/',
      is_premium: true,
    },
    {
      id: 16,
      name: 'Ejemplo41833',
      surname: 'Vet16',
      email_adress: 'ejemplo221@gmail.com',
      adress: 'Calle ejemplo 2322',
      telephone: '486359613',
      optional_photo: 'http://www.ejemplo543.com/',
      is_premium: false,
    },
    {
      id: 17,
      name: 'Ejemplo18233',
      surname: 'Vet17',
      email_adress: 'ejemplo176@gmail.com',
      adress: 'Calle ejemplo 7522',
      telephone: '486359557',
      optional_photo: 'http://www.ejemplo202.com/',
      is_premium: true,
    },
    {
      id: 18,
      name: 'E2jemplo1833',
      surname: 'Vet18',
      email_adress: 'ejemplo251@gmail.com',
      adress: 'Calle ejemplo 232',
      telephone: '666669615',
      optional_photo: 'http://www.ejemplo287.com/',
      is_premium: false,
    },
  ]);
};
